ALTER TABLE [dbo].[tbInstance]
    ADD CONSTRAINT [PK_tbInstance] PRIMARY KEY CLUSTERED ([InstanceKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

