ALTER TABLE [dbo].[tbStudy]
    ADD CONSTRAINT [PK_tbStudy] PRIMARY KEY CLUSTERED ([StudyKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

