ALTER TABLE [dbo].[tbSeries]
    ADD CONSTRAINT [PK_tbSeries] PRIMARY KEY CLUSTERED ([SeriesKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

